apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster/cicd/newChart-0.1.0.tgz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: remote
