apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: default
spec:
  #serviceAccountName: remote-sa
  kubeConfig:
    secretRef:
      name: remote-cluster-config
  chart:
    spec:
      chart: app-cluster/newChart-0.1.0.tgz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: remote-deploy
  interval: 1m0s
  targetNamespace: default
